
package com.thejavageek.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "erreur", targetNamespace = "http://www.enedis.fr/sge/b2b/technique/v1.0")
public class Erreur
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErreurType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Erreur(String message, ErreurType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Erreur(String message, ErreurType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.thejavageek.client.ErreurType
     */
    public ErreurType getFaultInfo() {
        return faultInfo;
    }

}
