
package com.thejavageek.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecherchePointV2.0", targetNamespace = "http://www.enedis.fr/sge/b2b/services", wsdlLocation = "file:/home/ec2-user/webapi/Enedis.SGE.GUI.0427.B2B%20RecherchePointV2.0_v1.0/Services/RecherchePoint/RecherchePoint-v2.0.wsdl")
public class RecherchePointV20
    extends Service
{

    private final static URL RECHERCHEPOINTV20_WSDL_LOCATION;
    private final static WebServiceException RECHERCHEPOINTV20_EXCEPTION;
    private final static QName RECHERCHEPOINTV20_QNAME = new QName("http://www.enedis.fr/sge/b2b/services", "RecherchePointV2.0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/x1-l/PIMA/webapi/Enedis.SGE.GUI.0427.B2B%20RecherchePointV2.0_v1.0/Services/RecherchePoint/RecherchePoint-v2.0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECHERCHEPOINTV20_WSDL_LOCATION = url;
        RECHERCHEPOINTV20_EXCEPTION = e;
    }

    public RecherchePointV20() {
        super(__getWsdlLocation(), RECHERCHEPOINTV20_QNAME);
    }

    public RecherchePointV20(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECHERCHEPOINTV20_QNAME, features);
    }

    public RecherchePointV20(URL wsdlLocation) {
        super(wsdlLocation, RECHERCHEPOINTV20_QNAME);
    }

    public RecherchePointV20(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECHERCHEPOINTV20_QNAME, features);
    }

    public RecherchePointV20(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecherchePointV20(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecherchePointPortType
     */
    @WebEndpoint(name = "RecherchePointPort")
    public RecherchePointPortType getRecherchePointPort() {
        return super.getPort(new QName("http://www.enedis.fr/sge/b2b/services", "RecherchePointPort"), RecherchePointPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecherchePointPortType
     */
    @WebEndpoint(name = "RecherchePointPort")
    public RecherchePointPortType getRecherchePointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.enedis.fr/sge/b2b/services", "RecherchePointPort"), RecherchePointPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECHERCHEPOINTV20_EXCEPTION!= null) {
            throw RECHERCHEPOINTV20_EXCEPTION;
        }
        return RECHERCHEPOINTV20_WSDL_LOCATION;
    }

}
