
package com.thejavageek.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.ResponseWrapper;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecherchePointPortType", targetNamespace = "http://www.enedis.fr/sge/b2b/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecherchePointPortType {


    /**
     * 
     * @param loginUtilisateur
     * @param criteres
     * @return
     *     returns com.thejavageek.client.PointsType
     * @throws Erreur
     */
    @WebMethod
    @WebResult(name = "points", targetNamespace = "")
    @RequestWrapper(localName = "rechercherPoint", targetNamespace = "http://www.enedis.fr/sge/b2b/services/rechercherpoint/v2.0", className = "com.thejavageek.client.RechercherPointType")
    @ResponseWrapper(localName = "rechercherPointResponse", targetNamespace = "http://www.enedis.fr/sge/b2b/services/rechercherpoint/v2.0", className = "com.thejavageek.client.RechercherPointResponseType")
    public PointsType rechercherPoint(
            @WebParam(name = "criteres", targetNamespace = "")
                    CriteresType criteres,
            @WebParam(name = "loginUtilisateur", targetNamespace = "")
                    String loginUtilisateur)
        throws Erreur
    ;

}
